# Generated by Django 3.2.5 on 2021-07-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'description', 'image']},
        ),
    ]
